import Container from './components/Container';
import Button from './components/Button';
import ProjectCard from './components/ProjectCard';
import TechCard from './components/TechCard';

export const metadata = {
  title: "Noah Kaiser - Portfolio",
  description: "Generated by create next app",
};

export default function Portfolio() {
  return (
    <Container id="content">
      <h1 className='section'>Hey!</h1><br />
      <h1>I'm Noah Kaiser</h1>
      <span className='description'>I am a Computer Science Major from James Madison University
        focused on Web Development.
      </span>
      <Button id="learn-more-btn" href='/#about'>Learn More</Button>
      <h1 id='projects' className='section'>Projects</h1>
      <hr />
      <Container className="project-container">
        <ProjectCard
          imageSrc="/crossyoff.png"
          title="CrossyOff"
          desc="Site for managing player data for the Competitive Crossy Road Community"
          stack={["Node", "React", "CSS", "MySQL"]}
          sourceURL="https://github.com/hfsyntax/crossyoff"
          appURL="https://crossyoff.vercel.app/"
        />
        <ProjectCard
          imageSrc="/pick6.png"
          title="Pick6"
          desc="Site for managing NFL fantasy football selections."
          stack={["HTML", "JavaScript", "CSS", "PHP", "MySQL"]}
          sourceURL="https://github.com/hfsyntax/pick6"
          appURL="https://pick-6.net/"
        />
        <ProjectCard
          imageSrc="/biomium.png"
          title="Biomium"
          desc="Browser extension for the website game biome3d.com"
          stack={["Node", "JavaScript", "CSS", "Tampermonkey"]}
          sourceURL="https://github.com/hfsyntax/biomium"
          appURL="http://biome3d.com/"
        />
        <ProjectCard imageSrc="/chick.png" title="Chick" desc="Bot for managing the Competitive Crossy Road Community Discord Server" stack={["Node"]} />
      </Container>
      <h1 id='technologies' className='section'>Technologies</h1>
      <hr />
      <span className='description'>
        I have experience with both front-end and back-end technologies.
        However, I prefer working with front-end technologies because I enjoy creating user interfaces.
      </span>
      <Container className="tech-card-container">
        <TechCard />
      </Container>
      <h1 id='about' className='section'>About Me</h1>
      <hr />
      <span className='description'>
        I learned about the concept of programming through wanting to make a websites game interface better.
        In the process of creating the interface I realized programming could be used to improve applications
        functionality and maintainability.
        I began to use programming as a tool to create features for communities I started.
      </span>
    </Container>
  );
}
